// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo2svi1nS61X5eBSYTLPnTN339GmcruV0',
    appId: '1:429762482636:web:bf250175ca49e699be4d69',
    messagingSenderId: '429762482636',
    projectId: 'kigali-city-directory-8e51a',
    authDomain: 'kigali-city-directory-8e51a.firebaseapp.com',
    storageBucket: 'kigali-city-directory-8e51a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQUIc608SRHnaeebfY3qvRbBP5u1Da-Rk',
    appId: '1:429762482636:android:ffcff1f2c34bddd9be4d69',
    messagingSenderId: '429762482636',
    projectId: 'kigali-city-directory-8e51a',
    storageBucket: 'kigali-city-directory-8e51a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2R3WWgucRLnW5XvTzTWGieXk_P8uGLR0',
    appId: '1:429762482636:ios:d18a2c74d136a82dbe4d69',
    messagingSenderId: '429762482636',
    projectId: 'kigali-city-directory-8e51a',
    storageBucket: 'kigali-city-directory-8e51a.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2R3WWgucRLnW5XvTzTWGieXk_P8uGLR0',
    appId: '1:429762482636:ios:d18a2c74d136a82dbe4d69',
    messagingSenderId: '429762482636',
    projectId: 'kigali-city-directory-8e51a',
    storageBucket: 'kigali-city-directory-8e51a.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo2svi1nS61X5eBSYTLPnTN339GmcruV0',
    appId: '1:429762482636:web:a6c854e00eeca0c2be4d69',
    messagingSenderId: '429762482636',
    projectId: 'kigali-city-directory-8e51a',
    authDomain: 'kigali-city-directory-8e51a.firebaseapp.com',
    storageBucket: 'kigali-city-directory-8e51a.firebasestorage.app',
  );
}
